name: cpplint

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cpplint
        run: |
          python -m pip install --upgrade pip
          pip install cpplint

      - name: Run cpplint (include/src only)
        id: cpplint
        shell: bash
        run: |
          set -o pipefail
          mkdir -p reports
          python -m cpplint --recursive include src 2>&1 | tee reports/cpplint_report.txt
          echo "exit_code=${PIPESTATUS[0]}" >> "$GITHUB_OUTPUT"

      - name: Upload cpplint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cpplint-report
          path: reports/cpplint_report.txt

      - name: Fail if cpplint found issues
        if: steps.cpplint.outputs.exit_code != '0'
        env:
          CPPLINT_EXIT: ${{ steps.cpplint.outputs.exit_code }}
        run: |
          echo "cpplint found issues (exit $CPPLINT_EXIT)"
          exit 1


